### ISSUE TITLE
New Project Name!

### ISSUE THREAD

**Issue by billycao** [billycao/Wi-Mote#4]
@james-h @Saqib117 @Sayan- 

I'm planning on buying a domain name and working on a site for this project, we discussed how Wi-Mote has its problems, anyone have any name suggestions?

Do we want a creative name or a name that reflects what this app does? Hopefully both?

Any ideas?

**Comment by Saqib117** [comment]
What's your timeline for this? or is it still loose. It might be good to wait on the investing in a domain until after we are ready for initial release next Q. I feel as we add changes and stuff we'll get a better idea, etc. also don't wanna work on this during finals Lol. 

As for the name, it should definitely reflect what it does, in a creative way. We want users to instantly know what sort of app this is by the name, but not necessarily be bored by it.

**Comment by billycao** [comment]
No timeline at all, but not at the very end, since I want to at least create some mockups with the new name sometime. Maybe end of Spring Break?

I don't want to work on it before finals either LOL.

**Comment by Saqib117** [comment]
I had some ideas, one being "droidmote" but it turns out a few days ago someone released a similar app to ours with that name

you guys should check it out, it's a little different than ours but looks nice. maybe get ideas from them?

**Comment by ghost** [comment]
"becausemote" lol jk xD

How about we turn the "W" upside down to get "Mi-Mote"? "Mi" as "My".

So "Mi-Mote -- It's YOUR remote! Different modes to suit your needs and lifestyle. Customizable options for maximum flexibility. The next-generation wireless PC remote is here!"

**Comment by Saqib117** [comment]
That's an interesting idea James... i'm not sure how i feel about it, but i think it might have potential.

also.. when did our git repo change the main menu to say "droid play" O_o and it's baby blue? haha and it still says because :-p

**Comment by ghost** [comment]
I believe @billycao changed it like 3 days ago. Of course, the one I will submit tonight will still say "Wi-Mote". Also notice I fixed some bugs last night -- these bug fixes have been applied to both the submission version as well as our repo.

**Comment by billycao** [comment]
@Saqib117 I was just playing around with the UI, I'll change it back. I'm still thinking about UI/UX elements, I'll make a mockup for Mi-Mote, but keep brainstorming. :D

**Comment by billycao** [comment]
Oh also, since we're planning to put this repo under a new organization, we'd need an organization name too. :D

**Comment by ghost** [comment]
Hey all,

I guess I never mentioned this before, but I have my own website at http://www.crilogic.com/. If you guys want, I wouldn't mind hosting our project on there. Right now, my website contains some stuff I have done in the past (haven't updated it in a while). As you can see, my website is called CRILOGIC, so maybe we can also use that as our organization name?

James

**Comment by billycao** [comment]
I own a dedicated Linode box which hosts multiple sites, so I'd rather host the site on there. I'm fine with whatever organization name we want, but I'd rather buy another domain for the project itself. I'd imagine the others would want an organization name just for us though.

I can take responsibility for the domain and hosting and DNS once we think of a name for the project.

**Comment by Sayan-** [comment]
Hey guys,

Hope you had a good spring break. I've been drilling my creative friends
for some input on an organization/app name. I agree with Billy for having a
separate domain. You guys have any luck with figuring out the ICS bug over
break (or have any progress at that)?

I'm still in brainstorming stages for advanced gestures.

Best,
Sayan

On Sat, Mar 31, 2012 at 10:30 PM, Billy Cao <
reply@reply.github.com

**Comment by ghost** [comment]
Unfortunately now that I am back to my old phone, I only have Gingerbread to test (no ICS). Would you guys say it would be worthwhile to invest in a new phone, say the Galaxy Nexus?

**Comment by Saqib117** [comment]
@billycao I also agree with the app being hosted on it's own domain, 

as for the company name

@james-h if we use CRILOGIC, then you would be giving up your own name for our group. Would you really want that? because then all the stuff you have hosted there would either be taken to it's own section or moved. (just sepculating) otherwise i think it's a cool name, (and it seems to be the only one of it's kind, your website is on the top)

@all App name still eludes me. maybe we should meet up over lunch and brainstorm, it might be more effective in person. I did not get much time over spring break to change much, i fixed a few bugs (have not pushed yet) and i hope to change the layout of the accel mouse this week and then push a nice clean version.

**Comment by ghost** [comment]
@Saqib117 Since we have all agreed to host the app on a separate domain, I believe it would be best to **_not**_ use CRILOGIC as the organization name. Instead, we should come up with a new name as originally planned.

@ALL As a side note, you guys do realize that this project is still completely open-source at this point, so wouldn't it be too late to make this project closed-source, copyright it, and finally sell it? Others may already have our source code and be even working on an improved version based on our code. So unless we make any further improvements private, there is no way we can differentiate ourselves from what others may already have. Another option would be to keep the project free and open-source (like Linux), but I don't know how you guys would feel about that. Of course, I am fine with whatever you guys decide on, but I just wanted to share my thoughts.

**Comment by billycao** [comment]
@james-h On the open source point, I'm pretty comfortable with keeping it open source and having a closed license. Right now even though our source is open we have no licence, which means we retain the copyright on the sections of code we wrote. No one can use it because it's our intellectual property. However the issue remains that if someone really does we might not be able to stop them legally.

I was thinking if we wanted it to be closed we would create a GitHub org. account and just put it in there. Again that's dependent on a name, so keep brainstorming. I can make the GitHub and migrate the repo over and make it private once we have one.

And just like James, I'm also fine with either decision, as long as we're clear about licensing if we decide to make it open.

**Comment by Saqib117** [comment]
@billycao If having a closed licence means we can still sell it, then i'm fine with doing it that way too, but if we can only sell it by making it closed then lets do that. I'm not familiar with the differences so i will trust your take on that billy, but whatever we end up doing i would like an opportunity to sell it as our own.

@james-h aright, new name it is.. 

@all I still believe the best way to come up with a name would be a face to face chat among all 4 of us, and just throw ideas around until one sticks. it's hard to brainstorm with only one brain at a time.

**Comment by Sayan-** [comment]
Hey guys its been a while,

What if we use a QR code to validate every time rather than a pin? That way
we can get rid of that from every datagram. Cool.

Sayan

On Tue, Apr 3, 2012 at 12:00 PM, Saqib M. <
reply@reply.github.com

**Comment by billycao** [comment]
I like it, but pin would still have to be a backup mode for people who can't QR for whatever reason. 

Hope midterms are going well :P

**Comment by Saqib117** [comment]
Hello everyone, so Billy and I had a brunch and discussed some of the progress notes and issues of our app. The main topic that we discussed was the App name, given that we cannot progress on the website without it. 

We could not think of a decent name that would accurate depict what the app was for without it sounding kind of lame, so we decided maybe an acronym might be a good idea. after some brain storming we came to:

MARC (or MARK): or, what we thought so far..
Multiperpose (Multifunctional). 
Awesome (or accessible)
Remote
Control (or Kontrol)

we were debating on the K and C issue adn the "awesome" or "accessible" name, we thought awesome added just the right about of "fun" to our app to make it more appealing to users, afterall multiperpose, and remote control are pretty bland terms, and do accurately share the purpose, but what are your guys thoughts on that? Billy if you want to add more about our opinions feel free.

Other topics and progress notes i will add in the appropriate threads, this is only for the name.

**Comment by Sayan-** [comment]
Hey guys,

I made a few changes yesterday, but if we're at all interested in this
project we should probably migrate the repo into something that has
private repos, like bit bucket.

I'm fine with MARC/K but I think we might need the more/remote
explicitly in the title. What do you guys think about Smart-Mote?

On Mon, May 28, 2012 at 11:48 AM, Saqib M.
reply@reply.github.com
wrote:

**Comment by Saqib117** [comment]
Okay no one has replied about the app name, and i feel like this is one of the major obstacles that preventing me (and possibly others) to find a reason to continue. I would like to get the name set so we can start to think about the next step.

As far as i can tell there are two options. one being Marc as i explained above, and the other being Wimo as suggested by James. I like both, i am pretty neutral and see that both could have potential (because both sound like a name it would be easy to make a cartoon character to represent our app, as like the logo maybe?, just a thought)

anyhow please respond with what name you prefer, or if you have another idea and don't like either. 

Regards,
Saqib

**Comment by Saqib117** [comment]
oh Haha nice timing Sayan, replied right when i did. We could host the name like  "Marc, a remote for the future" (haha just a cheesy example) but the "name" of our app will be known as "marc" would that sort of idea work? so the app market can show a little more, almost like a sub title sort of thing.

Smart-Mote is okay too, a bit bland, but simple and clean, could work.

and i'm cool with migrating too, do you know how we could do that effectively?

**Comment by Sayan-** [comment]
I mean looking at bitbucket makes it so you can have a 5 user account
for free meaning we could have a team account and each get a person.
There should be a way to import and existing repo once we sign up. Of
course if we actually want to use bit bucket we should align our team
name to our product name. So we're back to this name thing XFD. Also
if you get a chance if you could test out the app on your phone that'd
be nice. IDK if my new method will work for older versions.

Play is literally the worst thing I have ever had to use in my life.
fml at work.

On Tue, Jul 10, 2012 at 12:17 PM, Saqib M.
reply@reply.github.com
wrote:

**Comment by billycao** [comment]
Either name works for me, I'd actually prefer Marc because it piques interest when discussed and shared, while Wimo and Smart-Mote sound too functional and less intriguing. 

It really doesn't matter though, someone should just make the call.

I support moving towards bitbucket because even though I'm biased towards GitHub they have free private repos which just works for us. I've just reformatted so I don't have my workstation set up for migration, so if someone wants to take ownership they can go ahead and do the migrate under one of the names.

Sorry I haven't been contributing as much, admittedly busy.
